version: '3'
services:
  demoapp:
    image: dockerdemo/sboot
    ports:
    - "8080:8080"
    networks:
      - demoappnet    
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
networks:
  demoappnet:               