//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 10:00:53 AM IST 
//

package com.intuit.cto.fds.dash.web.shared.rpc.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class AuthenticationInfoVO implements Serializable {

	private static final long serialVersionUID = 1L;

	protected String instructionTitle;
	protected String instructionText;
	protected List<AuthenticationMappingVO> authenticationMapping;

	public String getInstructionTitle() {
		return instructionTitle;
	}

	public void setInstructionTitle(String value) {
		this.instructionTitle = value;
	}

	public String getInstructionText() {
		return instructionText;
	}

	public void setInstructionText(String value) {
		this.instructionText = value;
	}

	public void setAuthenticationMapping(
			List<AuthenticationMappingVO> authenticationMapping) {
		this.authenticationMapping = authenticationMapping;
	}

	public List<AuthenticationMappingVO> getAuthenticationMapping() {
		if (authenticationMapping == null) {
			authenticationMapping = new ArrayList<AuthenticationMappingVO>();
		}
		return this.authenticationMapping;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("AuthenticationInfoVO [instructionTitle=");
		builder.append(instructionTitle);
		builder.append(", instructionText=");
		builder.append(instructionText);
		builder.append(", authenticationMapping=");
		builder.append(authenticationMapping);
		builder.append("]");
		return builder.toString();
	}

}
