//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:42:59 AM IST 
//


package com.intuit.cto.fds.dash.web.shared.rpc.dto;

import java.io.Serializable;
import java.util.List;


public class ChannelsVO implements Serializable {

	private static final long serialVersionUID = 1L;

    protected List<ChannelVO> channel;

	public List<ChannelVO> getChannel() {
		return channel;
	}

	public void setChannel(List<ChannelVO> channel) {
		this.channel = channel;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ChannelsVO [channel=");
		builder.append(channel);
		builder.append("]");
		return builder.toString();
	}


}
