//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 04:28:59 PM IST 
//

package com.intuit.cto.fds.dash.web.shared.rpc.dto;

import java.util.ArrayList;
import java.util.List;

public class EinProviderRelationshipsVO {

	protected List<EinProviderRelationshipVO> einProviderRelationship;

	public List<EinProviderRelationshipVO> getEinProviderRelationship() {
		if (einProviderRelationship == null) {
			einProviderRelationship = new ArrayList<EinProviderRelationshipVO>();
		}
		return this.einProviderRelationship;
	}

	public void setEinProviderRelationship(List<EinProviderRelationshipVO> einProviderRelationship) {
		this.einProviderRelationship = einProviderRelationship;
	}

	@Override
	public String toString() {
		return String.format("EinProviderRelationshipsVO [einProviderRelationship=%s]", einProviderRelationship);
	}

}
