//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 04:28:59 PM IST 
//


package com.intuit.cto.fds.dash.web.shared.rpc.dto;

public class EinVO {

    
    protected String ein;
  
    protected EinProviderRelationshipsVO einProviderRelationships;

    /**
     * Gets the value of the ein property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEin() {
        return ein;
    }

    /**
     * Sets the value of the ein property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEin(String value) {
        this.ein = value;
    }

    /**
     * Gets the value of the einProviderRelationships property.
     * 
     * @return
     *     possible object is
     *     {@link EinProviderRelationshipsVO }
     *     
     */
    public EinProviderRelationshipsVO getEinProviderRelationships() {
        return einProviderRelationships;
    }

    /**
     * Sets the value of the einProviderRelationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link EinProviderRelationshipsVO }
     *     
     */
    public void setEinProviderRelationships(EinProviderRelationshipsVO value) {
        this.einProviderRelationships = value;
    }

    @Override
	public String toString() {
		return String.format("EinVO [ein=%s, einProviderRelationships=%s]",
				ein, einProviderRelationships);
	}
}
