//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 04:25:32 PM IST 
//


package com.intuit.cto.fds.dash.web.shared.rpc.dto;

public class IntuitHostedVO
    extends ChannelVO
{

	private static final long serialVersionUID = 1L;

	public IntuitHostedVO() {
		preference = 3;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("IntuitHostedVO [super.toString()=");
		builder.append(super.toString());
		builder.append("]");
		return builder.toString();
	}
	

	public ChannelType typeOfChannel() {
		return ChannelType.INTUIT_HOSTED;
	}
}
