//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:42:59 AM IST 
//

package com.intuit.cto.fds.dash.web.shared.rpc.dto;

import java.io.Serializable;
import java.util.Date;

import javax.xml.datatype.XMLGregorianCalendar;


public class ServiceVO implements Serializable {

	private static final long serialVersionUID = 1L;

	
	protected String id;
	protected String name;
	
	protected String type;
	protected Boolean overwrite;
	protected String availabilityMessage;
	
	protected Date fullAvailabilityDate;
	
	protected Date partialAvailabilityDate;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the overwrite property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean getOverwrite() {
		return overwrite;
	}

	/**
	 * Sets the value of the overwrite property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOverwrite(Boolean value) {
		this.overwrite = value;
	}

	/**
	 * Gets the value of the fullAvailabilityDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getFullAvailabilityDate() {
		return fullAvailabilityDate;
	}

	/**
	 * Sets the value of the fullAvailabilityDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFullAvailabilityDate(Date value) {
		this.fullAvailabilityDate = value;
	}

	/**
	 * Gets the value of the partialAvailabilityDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getPartialAvailabilityDate() {
		return partialAvailabilityDate;
	}

	/**
	 * Sets the value of the partialAvailabilityDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setPartialAvailabilityDate(Date value) {
		this.partialAvailabilityDate = value;
	}

	 /**
     * Gets the value of the availabilityMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityMessage() {
        return availabilityMessage;
    }

    /**
     * Sets the value of the availabilityMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityMessage(String value) {
        this.availabilityMessage = value;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ServiceVO [id=");
		builder.append(id);
		builder.append(", name=");
		builder.append(name);
		builder.append(", type=");
		builder.append(type);
		builder.append(", overwrite=");
		builder.append(overwrite);
		builder.append(", availabilityMessage=");
		builder.append(availabilityMessage);
		builder.append(", fullAvailabilityDate=");
		builder.append(fullAvailabilityDate);
		builder.append(", partialAvailabilityDate=");
		builder.append(partialAvailabilityDate);
		builder.append("]");
		return builder.toString();
	}

}
