CREATE TABLE "DRIVER"
  (
    "ID"   VARCHAR2(40 BYTE),
    "NAME" VARCHAR2(100 BYTE),
    CONSTRAINT "DRIVER_PK" PRIMARY KEY ("ID")
  ) ;
CREATE TABLE "DRIVER_LOCATION"
  (
    "ID"        VARCHAR2(40 BYTE),
    "DRIVER_ID" VARCHAR2(40 BYTE),
    "LAT"       VARCHAR2(20 BYTE),
    "LON"       VARCHAR2(20 BYTE),
    CONSTRAINT "DRIVER_LOCATION_PK" PRIMARY KEY ("ID")
  )
