-- Below DDL is for Ticket creation API
CREATE
  TABLE TICKET
  (
    TICKET_ID BIGINT NOT NULL,
    TICKET_DESCRIPTION   VARCHAR(255),
    PRIORITY_LEVEL       VARCHAR(100),
    ERROR_CODE           VARCHAR(100),
    REFRESH_STATUS       VARCHAR(255),
    TICKET_TYPE          VARCHAR(100),
    STATUS_NAME          VARCHAR(100),
    ASSIGNED_TO          VARCHAR(100),
	UN_ASSIGNED          VARCHAR(10) DEFAULT NULL,
    DUE_DATE             TIMESTAMP DEFAULT NULL,
    SCRIPT_NAME          VARCHAR(100),
    PARENT_TICKET_ID VARCHAR(100),
	PEER_REVIEWER VARCHAR(100),
	REVIEW_ID VARCHAR(100),
	REVIEW_COMMENTS CLOB DEFAULT NULL,
	CLOSING_COMMENTS CLOB DEFAULT NULL,
    CREATED_BY           VARCHAR(100),
    CREATED_DT           TIMESTAMP DEFAULT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DT          TIMESTAMP DEFAULT NULL,
    CASE_ID 			 VARCHAR(20) DEFAULT NULL,
    CONSTRAINT PK_TICKET_ID PRIMARY KEY (TICKET_ID)
  );
CREATE
  TABLE TICKET_PRIORITY
  (
    PRIORITY_LEVEL VARCHAR(100),
    SLA_HOURS BIGINT,
    CREATED_BY  VARCHAR(100),
    CREATED_DT  TIMESTAMP DEFAULT NULL,
    MODIFIED_BY VARCHAR(100),
    MODIFIED_DT TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_FDS_TICKET_PRIORITY PRIMARY KEY (PRIORITY_LEVEL)
  );
CREATE
  TABLE TICKET_STATUS
  (
    STATUS_NAME  VARCHAR(100),
    STATUS_GROUP VARCHAR(255),
    CREATED_BY   VARCHAR(100),
    CREATED_DT   TIMESTAMP DEFAULT NULL,
    MODIFIED_BY  VARCHAR(100),
    MODIFIED_DT  TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_FDS_TICKET_STATUS PRIMARY KEY (STATUS_NAME)
  );
CREATE
  TABLE ERROR_CODE
  (
    ERROR_CODE     VARCHAR(100),
    ERROR_CATEGORY VARCHAR(255),
    DESCRIPTION    VARCHAR(255),
    CREATED_BY     VARCHAR(100),
    CREATED_DT     TIMESTAMP DEFAULT NULL,
    MODIFIED_BY    VARCHAR(100),
    MODIFIED_DT    TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_FDS_ERROR_CODE PRIMARY KEY (ERROR_CODE)
  );
CREATE
  TABLE TICKET_TITLES
  (
    TITLE_IDENTIFIER VARCHAR(255),
    TICKET_ID BIGINT,
    CUSTOMER_IDENTIFIER VARCHAR(255),
	CUSTOMER_ID_TYPE VARCHAR(255),
    PROVIDER_ID         VARCHAR(255),
    CREATED_BY          VARCHAR(100),
    CREATED_DT          TIMESTAMP DEFAULT NULL,
    MODIFIED_BY         VARCHAR(100),
    MODIFIED_DT         TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_FDS_TICKET_TITLES PRIMARY KEY (TITLE_IDENTIFIER)
  );
CREATE
  TABLE TICKET_SOURCE_SUMMARY
  (
    SOURCE_SUMMARY_ID       VARCHAR(255),
    TITLE_IDENTIFIER        VARCHAR(255),
    SOURCE_ISSUE_IDENTIFIER VARCHAR(100),
    SOURCE_SUBJECT          VARCHAR(255),
    SOURCE                  VARCHAR(255),
    CREATED_BY              VARCHAR(100),
    CREATED_DT              TIMESTAMP DEFAULT NULL,
    MODIFIED_BY             VARCHAR(100),
    MODIFIED_DT             TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_SOURCE_SUMMARY_ID PRIMARY KEY (SOURCE_SUMMARY_ID)
  );
CREATE
  TABLE TICKET_TYPE
  (
    TICKET_TYPE             VARCHAR(100),
    CREATED_BY              VARCHAR(100),
    CREATED_DT              TIMESTAMP DEFAULT NULL,
    MODIFIED_BY             VARCHAR(100),
    MODIFIED_DT             TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_SOURCE_TYPE_ID PRIMARY KEY (TICKET_TYPE)
  );
CREATE
  TABLE TICKET_IMPACTED_ACCOUNTS
  (
    IMPACTED_ACCOUNT_ID VARCHAR(255),
    TITLE_IDENTIFIER    VARCHAR(255),
    ACCOUNT_IDENTIFIER  VARCHAR(255),
    CREDENTIAL_SET_ID   VARCHAR(255),
    ERROR_CODE          VARCHAR(100),
    CREATED_BY          VARCHAR(100),
    CREATED_DT          TIMESTAMP DEFAULT NULL,
    MODIFIED_BY         VARCHAR(100),
    MODIFIED_DT         TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_IMPACTED_ACCOUNT_ID PRIMARY KEY (IMPACTED_ACCOUNT_ID)
  );
CREATE
  TABLE TICKET_HISTORY
  (
    TICKET_HISTORY_ID VARCHAR(255),
    TICKET_ID BIGINT,
    DATE_FROM    TIMESTAMP DEFAULT NULL,
    DATE_TO      TIMESTAMP DEFAULT NULL,
    STATUS_NAME      VARCHAR(255),
	PRIORITY_LEVEL 	VARCHAR(255),
	ASSIGNED_TO  VARCHAR(255),
	UN_ASSIGNED VARCHAR(10) DEFAULT NULL,
	TICKET_TYPE VARCHAR(255),
	NOTES CLOB DEFAULT NULL,
	ACTIVTIY_DONE VARCHAR(255),
	CREATED_BY  VARCHAR(255),
    CREATED_DT  TIMESTAMP DEFAULT NULL,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DT TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_TICKET_HISTORY_ID PRIMARY KEY (TICKET_HISTORY_ID)
  );

CREATE
  TABLE TICKET_ATTACHMENT
  (
    ATTACHMENT_ID VARCHAR(100) NOT NULL,
    TICKET_ID BIGINT,
    FILE_NAME VARCHAR(100),
    FILE_TYPE VARCHAR(100),
    ATTACHMENT_DATA BLOB,
    CREATED_BY  VARCHAR(100),
    CREATED_DT  TIMESTAMP DEFAULT NULL,
    MODIFIED_BY VARCHAR(100),
    MODIFIED_DT TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_ATTACHMENT_ID PRIMARY KEY (ATTACHMENT_ID)
  );
CREATE
  TABLE TICKET_PANEL
  (
    PANEL_NAME  VARCHAR(100) NOT NULL,
    CREATED_BY  VARCHAR(100) NOT NULL,
    CREATED_DT  TIMESTAMP DEFAULT NULL,
    MODIFIED_BY VARCHAR(100) NOT NULL,
    MODIFIED_DT TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (PANEL_NAME)
  );
CREATE
  TABLE PANEL_SELECTION
  (
    SELECTION_ID  VARCHAR(100) NOT NULL,
    USER_ROLE     VARCHAR(100) NOT NULL,
    TICKET_STATUS VARCHAR(100) NOT NULL,
    TICKET_TYPE   VARCHAR(100) NOT NULL,
    CREATED_BY    VARCHAR(100) NOT NULL,
    CREATED_DT    TIMESTAMP DEFAULT NULL,
    MODIFIED_BY   VARCHAR(100) NOT NULL,
    MODIFIED_DT   TIMESTAMP DEFAULT NULL,
    PANEL_NAME    VARCHAR(100) NOT NULL,
    PRIMARY KEY (SELECTION_ID),
    CONSTRAINT FK_PANEL_NAME FOREIGN KEY (PANEL_NAME) REFERENCES TICKET_PANEL (
    PANEL_NAME)
  );
CREATE
  TABLE TICKET_ELEVATION
  (
    ELEVATION_ID          VARCHAR(100) NOT NULL,
    CURRENT_TICKET_STATUS VARCHAR(100) NOT NULL,
    USER_ROLE             VARCHAR(100) NOT NULL,
    NEXT_TICKET_STATUS    VARCHAR(100) NOT NULL,
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DT            TIMESTAMP DEFAULT NULL,
    MODIFIED_BY           VARCHAR(100) NOT NULL,
    MODIFIED_DT           TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (ELEVATION_ID),
    CONSTRAINT FK_CURRENT_TICKET_STATUS FOREIGN KEY (CURRENT_TICKET_STATUS)
    REFERENCES TICKET_STATUS (STATUS_NAME),
    CONSTRAINT FK_NEXT_TICKET_STATUS FOREIGN KEY (NEXT_TICKET_STATUS)
    REFERENCES TICKET_STATUS (STATUS_NAME)
  );
  
CREATE TABLE CLOSING_COMMENTS (
  COMMENT_ID VARCHAR(100) NOT NULL,
  PROVIDER_ID VARCHAR(45) DEFAULT NULL,
  SCRIPT_NAME VARCHAR(100) DEFAULT NULL,
  ERROR_CODE VARCHAR(100) DEFAULT NULL,
  SCENARIO VARCHAR(100) DEFAULT NULL,
  CLOSING_COMMENTS CLOB DEFAULT NULL,
  ACTIVE_FLAG CHAR(1) DEFAULT 'Y',
  CREATED_BY VARCHAR(100) DEFAULT NULL,
  CREATED_DT timestamp DEFAULT NULL,
  MODIFIED_BY VARCHAR(100) DEFAULT NULL,
  MODIFIED_DT timestamp DEFAULT NULL,
  PRIMARY KEY (COMMENT_ID),
  CONSTRAINT FK_ERROR_CODES FOREIGN KEY (ERROR_CODE) REFERENCES ERROR_CODE (ERROR_CODE)
);

CREATE
  TABLE OPEN_DOMAIN
  (
    DOMAIN_ID   VARCHAR(36) NOT NULL,
    NAME        VARCHAR(300) NOT NULL UNIQUE,
    CREATED_BY  VARCHAR(255),
    CREATED_DT  TIMESTAMP DEFAULT NULL,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DT TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_DOMAIN_ID PRIMARY KEY (DOMAIN_ID)
  );
CREATE
  TABLE PROVIDER_DOMAIN
  (
    VALID_DOMAIN_ID VARCHAR(36) NOT NULL,
    PROVIDER_ID     VARCHAR(300) NOT NULL,
    NAME            VARCHAR(300) NOT NULL,
    CREATED_BY      VARCHAR(255),
    CREATED_DT      TIMESTAMP DEFAULT NULL,
    MODIFIED_BY     VARCHAR(255),
    MODIFIED_DT     TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_VALID_DOMAIN_ID PRIMARY KEY (VALID_DOMAIN_ID)
  );
CREATE
  TABLE HTML_KEY
  (
    KEY_ID           VARCHAR(36) NOT NULL,
    PROVIDER_ID      VARCHAR(300) NOT NULL,
    ELEMENT_TYPE     VARCHAR(100) NOT NULL,
    ELEMENT_POSITION INT NOT NULL,
    ATTR_NAME        VARCHAR(100) NOT NULL,
    ATTR_VALUE       VARCHAR(255) NOT NULL,
    PAGE_SIGNATURE   VARCHAR(255) NOT NULL,
    JOB_TYPE         VARCHAR(100) NOT NULL,
    CREATED_BY       VARCHAR(255),
    CREATED_DT       TIMESTAMP DEFAULT NULL,
    MODIFIED_BY      VARCHAR(255),
    MODIFIED_DT      TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_KEY_ID PRIMARY KEY (KEY_ID)
  );
CREATE
  TABLE PROFILE
  (
    PROFILE_ID   VARCHAR(36) NOT NULL,
    PROVIDER_ID  VARCHAR(300) NOT NULL,
    PROFILE_TYPE VARCHAR(100) NOT NULL,
    FILTER_TYPE  VARCHAR(100) NOT NULL,
    CREATED_BY   VARCHAR(255),
    CREATED_DT   TIMESTAMP DEFAULT NULL,
    MODIFIED_BY  VARCHAR(255),
    MODIFIED_DT  TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_PROFILE_ID PRIMARY KEY (PROFILE_ID)
  );
CREATE
  TABLE RULES
  (
    RULE_ID     VARCHAR(36) NOT NULL,
    PROFILE_ID  VARCHAR(36),
    FIELD_VALUE VARCHAR(300) NOT NULL,
    FILTER_TYPE VARCHAR(100) NOT NULL,
    PROVIDER_ID  VARCHAR(300) NOT NULL,
    CREATED_BY  VARCHAR(100),
    CREATED_DT  TIMESTAMP DEFAULT NULL,
    MODIFIED_BY VARCHAR(100),
    MODIFIED_DT TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_RULE_ID PRIMARY KEY (RULE_ID)
  );
  
  	CREATE TABLE WRAPPER_CLASS 
   ( WRAPPER_ID VARCHAR(36) NOT NULL, 
	 WRAPPER_TYPE   VARCHAR(100), 
     WRAPPER_NAME  VARCHAR(100), 
     CREATED_BY    VARCHAR(100),
     CREATED_DT    TIMESTAMP DEFAULT NULL,
     MODIFIED_BY   VARCHAR(100),
     MODIFIED_DT   TIMESTAMP DEFAULT NULL,
	 CONSTRAINT PK_WRAPPER_ID  PRIMARY KEY (WRAPPER_ID)
	);

			
    CREATE TABLE PROVIDER_WRAPPER_MAPPING 
   ( PROVIDER_WRAPPER_ID VARCHAR(36) NOT NULL, 
	 PROVIDER_ID   VARCHAR(255), 
     WRAPPER_TYPE   VARCHAR(100), 
     WRAPPER_NAME  VARCHAR(100), 
     CREATED_BY    VARCHAR(100),
     CREATED_DT    TIMESTAMP DEFAULT NULL,
     MODIFIED_BY   VARCHAR(100),
     MODIFIED_DT   TIMESTAMP DEFAULT NULL,
	 CONSTRAINT PK_PROVIDER_WRAPPER_ID PRIMARY KEY (PROVIDER_WRAPPER_ID)
	)
	
  CREATE TABLE JSON_FILTER
   ( FILTER_ID VARCHAR(36) NOT NULL, 
     PROVIDER_ID   VARCHAR(100), 
     IS_MASKED  CHAR(1) DEFAULT 'Y', 
     CREATED_BY    VARCHAR(100),
     CREATED_DT    TIMESTAMP DEFAULT NULL,
     MODIFIED_BY   VARCHAR(100),
     MODIFIED_DT   TIMESTAMP DEFAULT NULL,
	 CONSTRAINT PK_FILTER_ID  PRIMARY KEY (FILTER_ID)
	);
	
	CREATE TABLE JSON_RULES
   ( RULE_ID VARCHAR(36) NOT NULL, 
     FILTER_ID   VARCHAR(36), 
     FIELD_VALUE   VARCHAR(100), 
     CREATED_BY    VARCHAR(100),
     CREATED_DT    TIMESTAMP DEFAULT NULL,
     MODIFIED_BY   VARCHAR(100),
     MODIFIED_DT   TIMESTAMP DEFAULT NULL,
	 CONSTRAINT PK_JSON_RULE_ID PRIMARY KEY (RULE_ID)
	);
	
	CREATE TABLE AUDIT_TABLE
   (
     AUDIT_ID VARCHAR(36) NOT NULL, 
	 USER_ID VARCHAR(100) NOT NULL,
     COMPONENT_NAME  VARCHAR(100),
	 CUSTOM_FIELD_1 VARCHAR(100),
	 CUSTOM_FIELD_2 VARCHAR(100),
	 CUSTOM_FIELD_3 VARCHAR(100),
     CUSTOM_FIELD_4 VARCHAR(100),
     CREATED_BY    VARCHAR(100),
     CREATED_DT    TIMESTAMP DEFAULT NULL,
	 CONSTRAINT PK_AUDIT_ID  PRIMARY KEY (AUDIT_ID)
	);
	
	
ALTER TABLE JSON_RULES ADD CONSTRAINT FK_FILTER_ID FOREIGN KEY (FILTER_ID)
REFERENCES JSON_FILTER (FILTER_ID);
ALTER TABLE TICKET ADD CONSTRAINT ERROR_CODE FOREIGN KEY (ERROR_CODE)
REFERENCES ERROR_CODE (ERROR_CODE);
ALTER TABLE TICKET_TITLES ADD CONSTRAINT FK_TICKET_ID FOREIGN KEY (
TICKET_ID) REFERENCES TICKET (TICKET_ID);
ALTER TABLE TICKET_SOURCE_SUMMARY ADD CONSTRAINT FK_TITLE_IDENTIFIER FOREIGN
KEY (TITLE_IDENTIFIER) REFERENCES TICKET_TITLES (TITLE_IDENTIFIER);
ALTER TABLE TICKET_IMPACTED_ACCOUNTS ADD CONSTRAINT FK_TITLE_ID_IMPACTED_ACCOUNTS FOREIGN KEY (TITLE_IDENTIFIER) 
REFERENCES TICKET_TITLES (TITLE_IDENTIFIER);
ALTER TABLE TICKET ADD CONSTRAINT FK_TICKET_TYPE FOREIGN KEY (TICKET_TYPE)
REFERENCES TICKET_TYPE (TICKET_TYPE);
ALTER TABLE TICKET ADD CONSTRAINT FK_STATUS_NAME FOREIGN KEY (STATUS_NAME)
REFERENCES TICKET_STATUS (STATUS_NAME);
ALTER TABLE TICKET ADD CONSTRAINT FK_PRIORITY_LEVEL FOREIGN KEY (PRIORITY_LEVEL)
REFERENCES TICKET_PRIORITY (PRIORITY_LEVEL);
ALTER TABLE TICKET_HISTORY ADD CONSTRAINT FK_TKT_HISTORY_TICKET_TYPE FOREIGN KEY (TICKET_TYPE)
REFERENCES TICKET_TYPE (TICKET_TYPE);
ALTER TABLE TICKET_HISTORY ADD CONSTRAINT FK_TKT_HISTORY_STATUS_NAME FOREIGN KEY (STATUS_NAME)
REFERENCES TICKET_STATUS (STATUS_NAME);
ALTER TABLE TICKET_HISTORY ADD CONSTRAINT FK_TKT_HISTORY_PRIORITY_LEVEL FOREIGN KEY (PRIORITY_LEVEL)
REFERENCES TICKET_PRIORITY (PRIORITY_LEVEL);
ALTER TABLE TICKET_IMPACTED_ACCOUNTS ADD CONSTRAINT FK_ERROR_CODE_IMPACTED_ACCTS FOREIGN KEY (ERROR_CODE) 
REFERENCES ERROR_CODE (ERROR_CODE);
ALTER TABLE TICKET_HISTORY ADD CONSTRAINT FK_TICKET_ID_TICKET_AUDIT FOREIGN
KEY (TICKET_ID) REFERENCES TICKET (TICKET_ID);
ALTER TABLE TICKET_ATTACHMENT ADD CONSTRAINT FK_TICKET_ID_TICKET_ATTACHMENT
FOREIGN KEY (TICKET_ID) REFERENCES TICKET (TICKET_ID);
ALTER TABLE RULES ADD CONSTRAINT FK_PROFILE_ID FOREIGN KEY (PROFILE_ID)
REFERENCES PROFILE (PROFILE_ID);
ALTER TABLE RULES ADD CONSTRAINT UNQ_PROFILEID_PID_FIELD UNIQUE (PROFILE_ID, PROVIDER_ID, FIELD_VALUE);
