package com.nklmthr.mycode.game29.model;

public enum MATCH_PHASE {
	WAIT_FOR_LOGIN_ALL, WAIT_FOR_DEAL, WAIT_FOR_CHALLENGE_OR_DOUBLE, WAIT_FOR_CHALLENGE_REDOUBLE, WAIT_FOR_SET_TRUMP, WAIT_FOR_SHOW_TRUMP, WAIT_FOR_MATCH_FINISH
}
